# Project information
site_name: Agent Development Kit (ADK)
site_url: https://google.github.io/adk-docs
site_description: >-
  Build powerful multi-agent systems with Agent Development Kit (ADK)
site_dir: site
exclude_docs:
  api-reference/java/legal/*
not_in_nav: |
  /integrations/*.md

# Repository
repo_name: adk-docs
repo_url: https://github.com/google/adk-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright Google 2026&nbsp;&nbsp;|&nbsp;&nbsp;<a href="//policies.google.com/terms">Terms</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="//policies.google.com/privacy">Privacy</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#__consent">Manage cookies</a>

# Validation
validation:
  absolute_links: ignore

# Custom CSS
extra_css:
  - stylesheets/custom.css
  - stylesheets/language-tags.css

# Custom JavaScript
extra_javascript:
  - javascript/copy-page.js

# Additional config
extra:
  first_repo_url: https://github.com/google/adk-python
  first_repo_name: adk-python
  first_repo_icon: fontawesome/brands/github
  second_repo_url: https://github.com/google/adk-js
  second_repo_name: adk-js
  second_repo_icon: fontawesome/brands/github
  third_repo_url: https://github.com/google/adk-go
  third_repo_name: adk-go
  third_repo_icon: fontawesome/brands/github
  fourth_repo_url: https://github.com/google/adk-java
  fourth_repo_name: adk-java
  fourth_repo_icon: fontawesome/brands/github
  analytics:
    provider: google
    property: G-DKHZS27PHP
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize repeated visits and preferences,
      as well as to measure the effectiveness of our documentation and
      whether users find the information they need. With your consent,
      you're helping us to make our documentation better.

# Configuration
theme:
  name: material
  font:
    text: Google Sans
    code: Roboto Mono
  logo: assets/agent-development-kit.png
  favicon: assets/agent-development-kit.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true


# Plugins
plugins:
  - search
  - macros:
      module_name: scripts/integrations
      # Set custom delimiters for J2 templates to avoid conflicts with Markdown
      # alternative to {% %}
      j2_block_start_string: '{{%'
      j2_block_end_string: '%}}'
      # alternative to {{ }}
      j2_variable_start_string: '{{$'
      j2_variable_end_string: '$}}'
      # alternative to {# #}
      j2_comment_start_string: '{{#'
      j2_comment_end_string: '#}}'
  - redirects:
      redirect_maps:
        'get-started/local-testing.md': 'runtime/api-server.md'
        'get-started/tutorial.md': 'tutorials/index.md'
        'guides/responsible-agents.md': 'safety/index.md'
        'tools/third-party-tools.md': 'integrations/index.md'
        'tools/third-party/openapi-tools.md': 'tools-custom/openapi-tools.md'
        'tools/openapi-tools.md': 'tools-custom/openapi-tools.md'
        'tutorials/ag-ui.md': 'integrations/ag-ui.md'
        'tools/third-party/langchain.md': 'integrations/index.md'
        'tools/third-party/crewai.md': 'integrations/index.md'
        'get-started/testing.md': 'runtime/api-server.md'
        'tools/authentication.md': 'tools-custom/authentication.md'
        'tools/function-tools.md': 'tools-custom/function-tools.md'
        'tools/confirmation.md': 'tools-custom/confirmation.md'
        'tools/performance.md': 'tools-custom/performance.md'
        'tools/mcp-tools.md': 'tools-custom/mcp-tools.md'
        'tools/google-cloud/bigquery-agent-analytics.md': 'integrations/bigquery-agent-analytics.md'
        'tools/google-cloud-tools.md': 'integrations/index.md'
        'tools/built-in-tools.md': 'integrations/index.md'
        'sessions/rewind.md': 'sessions/session/rewind.md'
        'tools/third-party/ag-ui.md': 'integrations/ag-ui.md'
        'tools/google-cloud/api-registry.md': 'integrations/api-registry.md'
        'tools/google-cloud/apigee-api-hub.md': 'integrations/apigee-api-hub.md'
        'tools/google-cloud/application-integration.md': 'integrations/application-integration.md'
        'tools/third-party/asana.md': 'integrations/asana.md'
        'tools/third-party/atlassian.md': 'integrations/atlassian.md'
        'tools/google-cloud/bigquery.md': 'integrations/bigquery.md'
        'tools/google-cloud/bigtable.md': 'integrations/bigtable.md'
        'tools/third-party/cartesia.md': 'integrations/cartesia.md'
        'tools/third-party/chroma.md': 'integrations/chroma.md'
        'tools/google-cloud/code-exec-agent-engine.md': 'integrations/code-exec-agent-engine.md'
        'tools/gemini-api/code-execution.md': 'integrations/code-execution.md'
        'tools/gemini-api/computer-use.md': 'integrations/computer-use.md'
        'tools/google-cloud/data-agent.md': 'integrations/data-agent.md'
        'tools/third-party/daytona.md': 'integrations/daytona.md'
        'tools/third-party/elevenlabs.md': 'integrations/elevenlabs.md'
        'tools/google-cloud/express-mode.md': 'integrations/express-mode.md'
        'tools/third-party/github.md': 'integrations/github.md'
        'tools/third-party/gitlab.md': 'integrations/gitlab.md'
        'tools/google-cloud/gke-code-executor.md': 'integrations/gke-code-executor.md'
        'tools/gemini-api/google-search.md': 'integrations/google-search.md'
        'tools/third-party/hugging-face.md': 'integrations/hugging-face.md'
        'tools/third-party/linear.md': 'integrations/linear.md'
        'tools/google-cloud/mcp-toolbox-for-databases.md': 'integrations/mcp-toolbox-for-databases.md'
        'tools/third-party/mongodb.md': 'integrations/mongodb.md'
        'tools/third-party/n8n.md': 'integrations/n8n.md'
        'tools/third-party/notion.md': 'integrations/notion.md'
        'tools/third-party/paypal.md': 'integrations/paypal.md'
        'tools/third-party/postman.md': 'integrations/postman.md'
        'tools/google-cloud/pubsub.md': 'integrations/pubsub.md'
        'tools/third-party/qdrant.md': 'integrations/qdrant.md'
        'tools/google-cloud/spanner.md': 'integrations/spanner.md'
        'tools/third-party/stripe.md': 'integrations/stripe.md'
        'tools/google-cloud/vertex-ai-rag-engine.md': 'integrations/vertex-ai-rag-engine.md'
        'tools/google-cloud/vertex-ai-search.md': 'integrations/vertex-ai-search.md'
        'tools/index.md': 'integrations/index.md'
        'tools/gemini-api/index.md': 'integrations/index.md'
        'tools/google-cloud/index.md': 'integrations/index.md'
        'tools/third-party/index.md': 'integrations/index.md'
        'plugins/reflect-and-retry.md': 'integrations/reflect-and-retry.md'
        'observability/bigquery-agent-analytics.md': 'integrations/bigquery-agent-analytics.md'
        'observability/cloud-trace.md': 'integrations/cloud-trace.md'
        'observability/freeplay.md': 'integrations/freeplay.md'
        'observability/mlflow.md': 'integrations/mlflow.md'
        'observability/monocle.md': 'integrations/monocle.md'
        'observability/phoenix.md': 'integrations/phoenix.md'
        'observability/weave.md': 'integrations/weave.md'
        'observability/agentops.md': 'integrations/agentops.md'
        'observability/arize-ax.md': 'integrations/arize-ax.md'

  - llmstxt:
      markdown_description: An open-source, code-first toolkit for building, evaluating, and deploying sophisticated AI agents with flexibility and control.
      full_output: llms-full.txt
      sections:
        Build Agents:
        - get-started/*.md
        - tutorials/*.md
        - visual-builder/*.md
        - agents/*.md
        - integrations/*.md
        - tools/*.md
        - tools-custom/*.md
        - skills/*.md
        Run Agents:
        - runtime/*.md
        - deploy/*.md
        - observability/*.md
        - evaluate/*.md
        - safety/*.md
        Components:
        - context/*.md
        - sessions/*.md
        - callbacks/*.md
        - artifacts/*.md
        - events/*.md
        - apps/*.md
        - plugins/*.md
        - mcp/*.md
        - a2a/*.md
        - streaming/*.md
        - grounding/*.md
        Reference:
        - release-notes.md
        - api-reference/index.md
        - api-reference/rest/index.md
        - community.md
        - contributing-guide.md

# Navigation
nav:
  - Home:
    - index.md
  - Build Agents:
    - Get Started:
      - get-started/index.md
      - Python: get-started/python.md
      - TypeScript: get-started/typescript.md
      - Go: get-started/go.md
      - Java: get-started/java.md
    - Build your Agent:
      - tutorials/index.md
      - Multi-tool agent: get-started/quickstart.md
      - Agent team: tutorials/agent-team.md
      - Streaming agent:
        - get-started/streaming/index.md
        - Python: get-started/streaming/quickstart-streaming.md
        - Java: get-started/streaming/quickstart-streaming-java.md
      - Visual Builder: visual-builder/index.md
      - Coding with AI: tutorials/coding-with-ai.md
      - Advanced setup: get-started/installation.md
    - Agents:
      - agents/index.md
      - LLM agents: agents/llm-agents.md
      - Workflow agents:
        - agents/workflow-agents/index.md
        - Sequential agents: agents/workflow-agents/sequential-agents.md
        - Loop agents: agents/workflow-agents/loop-agents.md
        - Parallel agents: agents/workflow-agents/parallel-agents.md
      - Custom agents: agents/custom-agents.md
      - Multi-agent systems: agents/multi-agents.md
      - Agent Config: agents/config.md
    - Models for Agents:
      - agents/models/index.md
      - Gemini: agents/models/google-gemini.md
      - Claude: agents/models/anthropic.md
      - Vertex AI hosted: agents/models/vertex.md
      - Apigee AI Gateway: agents/models/apigee.md
      - Ollama: agents/models/ollama.md
      - vLLM: agents/models/vllm.md
      - LiteLLM: agents/models/litellm.md
    - Tools and Integrations:
      - integrations/index.md
    - Custom Tools:
      - tools-custom/index.md
      - Function tools:
        - Overview: tools-custom/function-tools.md
        - Tool performance: tools-custom/performance.md
        - Action confirmations: tools-custom/confirmation.md
      - MCP tools: tools-custom/mcp-tools.md
      - OpenAPI tools: tools-custom/openapi-tools.md
      - Authentication: tools-custom/authentication.md
      - Tool limitations: tools/limitations.md
    - Skills for Agents:
      - skills/index.md
  - Run Agents:
    - Agent Runtime:
      - Agent Runtime: runtime/index.md
      - Web Interface: runtime/web-interface.md
      - Command Line: runtime/command-line.md
      - API Server: runtime/api-server.md
      - Resume Agents: runtime/resume.md
      - Runtime Config: runtime/runconfig.md
      - Event Loop: runtime/event-loop.md
    - Deployment:
      - deploy/index.md
      - Agent Engine:
        - deploy/agent-engine/index.md
        - Standard deployment: deploy/agent-engine/deploy.md
        - Agent Starter Pack: deploy/agent-engine/asp.md
        - Test deployed agents: deploy/agent-engine/test.md
      - Cloud Run: deploy/cloud-run.md
      - GKE: deploy/gke.md
    - Observability:
      - observability/index.md
      - Logging: observability/logging.md
    - Evaluation:
      - evaluate/index.md
      - Criteria: evaluate/criteria.md
      - User Simulation: evaluate/user-sim.md
    - Safety and Security:
      - safety/index.md
  - Components:
    - Technical Overview: get-started/about.md
    - Context:
      - context/index.md
      - Context caching: context/caching.md
      - Context compression: context/compaction.md
    - Sessions & Memory:
      - sessions/index.md
      - Sessions:
        - sessions/session/index.md
        - Rewind sessions: sessions/session/rewind.md
        - Migrate sessions: sessions/session/migrate.md
      - State: sessions/state.md
      - Memory: sessions/memory.md
    - Callbacks:
      - callbacks/index.md
      - Types of callbacks: callbacks/types-of-callbacks.md
      - Callback patterns: callbacks/design-patterns-and-best-practices.md
    - Artifacts:
      - artifacts/index.md
    - Events:
      - events/index.md
    - Apps:
      - apps/index.md
    - Plugins:
      - plugins/index.md
    - MCP:
      - mcp/index.md
    - A2A Protocol:
      - a2a/index.md
      - Introduction to A2A: a2a/intro.md
      - A2A Quickstart (Exposing):
        - Python: a2a/quickstart-exposing.md
        - Go: a2a/quickstart-exposing-go.md
      - A2A Quickstart (Consuming):
        - Python: a2a/quickstart-consuming.md
        - Go: a2a/quickstart-consuming-go.md
    - Bidi-streaming (live):
      - streaming/index.md
      - Bidi-streaming development guide series:
        - Part 1. Intro to streaming: streaming/dev-guide/part1.md
        - Part 2. Sending messages: streaming/dev-guide/part2.md
        - Part 3. Event handling: streaming/dev-guide/part3.md
        - Part 4. Run configuration: streaming/dev-guide/part4.md
        - Part 5. Audio, Images, and Video: streaming/dev-guide/part5.md
      - Streaming Tools: streaming/streaming-tools.md
      - Configuring Bidi-streaming behavior: streaming/configuration.md
    - Grounding:
      - grounding/index.md
      - Google Search Grounding: grounding/google_search_grounding.md
      - Vertex AI Search Grounding: grounding/vertex_ai_search_grounding.md
  - Reference:
    - Release Notes: release-notes.md
    - API Reference:
      - api-reference/index.md
      - Python ADK: api-reference/python/index.html
      - Typescript ADK: api-reference/typescript/index.html
      - Go ADK: https://pkg.go.dev/google.golang.org/adk" target="_blank
      - Java ADK: api-reference/java/index.html
      - CLI Reference: api-reference/cli/index.html
      - Agent Config Reference: api-reference/agentconfig/index.html
      - REST API: api-reference/rest/index.md
    - Community Resources: community.md
    - Contributing Guide: contributing-guide.md
